---
- hosts: ubuntu
  user: ansible
  become: true
  tasks:
    - name: mvn install
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: yes
    - name: add group
      ansible.builtin.user:
        name: "ubuntu"
        group: "docker"
        append: yes
