---
- hosts: dev
  user: ansible
  become: yes
  tasks:
    - name: Add an Apt signing key, uses whichever key is at the URL
      ansible.builtin.apt_key:
      url: "{{keys}}"
      state: present
    - name: somerepo | apt source
      ansible.builtin.apt_repository:
        repo: "{{repos}}" 
        state: present
    - name: update and install jenkins
      ansible.builtin.apt:
        name: openjdk-8-jdk
        update_cache: yes
        state: present
      when:
        - ansible_facts['distribution'] == "Ubuntu"
        - ansible_facts['distribution_major_version'] == "18"
      vars:
        keys:
          - https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        repos:
          - 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
